# Generated by Django 5.1.1 on 2024-10-01 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25, unique=True, verbose_name='category name')),
                ('description', models.CharField(blank=True, help_text='an optional description for the category', max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='customer name')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact person')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='country')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=15, verbose_name='last name')),
                ('first_name', models.CharField(max_length=15, verbose_name='first name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/employee_photo/', verbose_name='photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=25, verbose_name='shipper name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'shipper',
                'verbose_name_plural': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='supplier name')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact person')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=15, null=True, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='order date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='demo.customer', verbose_name='customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='demo.employee', verbose_name='employee')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='demo.shipper', verbose_name='shipper')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product name')),
                ('unit', models.CharField(blank=True, max_length=25, null=True, verbose_name='unit')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='demo.category', verbose_name='category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='demo.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='demo.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='demo.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order detail',
                'verbose_name_plural': 'order details',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', '0')), name='order_detail_quantity_must_be_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', '0')), name='product_price_must_not_be_negative'),
        ),
    ]
